<?php
     $translations = [
        [
          "matchTime" => '15:15',
          "team_1" => 'Anastasia Pavlyuchenkova',
          "team_2" => 'Sara Errani',
          "ligaOf" => 'Rome Masters',
          "matchDate" => 10,
        ],
        [
          "matchTime" => '15:15',
          "team_1" => 'Elisabetta Cocciaretto',
          "team_2" => 'Lauren Davis',
          "ligaOf" => 'Rome Masters',
          "matchDate" => 10,
        ],
        [
          "matchTime" => '15:15',
          "team_1" => 'Franko Skugor/Raluca Olaru',
          "team_2" => 'Laslo Djere',
          "ligaOf" => 'Rome Masters',
          "matchDate" => 10,
        ],
        [
          "matchTime" => '17:00',
          "team_1" => 'Chennai Super Kings',
          "team_2" => 'Delhi Capitals',
          "ligaOf" => 'Indian Premier League',
          "matchDate" => 10,
        ],
        [
          "matchTime" => '20:40',
          "team_1" => 'Milwaukee Brewers',
          "team_2" => 'Los Angeles Dodgers',
          "ligaOf" => 'Major League Baseball',
          "matchDate" => 10,
        ],
        [
          "matchTime" => '21:00',
          "team_1" => 'Chelsea (W)',
          "team_2" => 'Leicester (W)',
          "ligaOf" => "English Women's Super League",
          "matchDate" => 10,
        ],
        [
          "matchTime" => '21:30',
          "team_1" => 'Brighton (W)',
          "team_2" => 'Arsenal (W)',
          "ligaOf" => "English Women's Super League",
          "matchDate" => 10,
        ],
        [
          "matchTime" => '21:45',
          "team_1" => 'Rangers (W)',
          "team_2" => 'Partick (W)',
          "ligaOf" => "Scottish Women's Premier League",
          "matchDate" => 10,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'AC Milan',
          "team_2" => 'Inter',
          "ligaOf" => 'UEFA Champions League',
          "matchDate" => 10,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Real Madrid',
          "team_2" => 'Partizan',
          "ligaOf" => 'Euro League (M)',
          "matchDate" => 10,
        ],

        [
          "matchTime" => '02:05',
          "team_1" => 'Florida Panthers',
          "team_2" => 'Toronto Maple Leafs',
          "ligaOf" => 'NHL',
          "matchDate" => 11,
        ],
        [
          "matchTime" => '02:40',
          "team_1" => 'Chicago Cubs',
          "team_2" => 'St Louis Cardinals',
          "ligaOf" => 'Major League Baseball',
          "matchDate" => 11,
        ],
        [
          "matchTime" => '12:50',
          "team_1" => 'Melbourne Storm',
          "team_2" => 'Brisbane Broncos',
          "ligaOf" => 'Australian NRL',
          "matchDate" => 11,
        ],
        [
          "matchTime" => '13:00',
          "team_1" => 'Surrey',
          "team_2" => 'Middlesex',
          "ligaOf" => 'LV County Championship',
          "matchDate" => 11,
        ],
        [
          "matchTime" => '17:00',
          "team_1" => 'Kolkata Knight Riders',
          "team_2" => 'Rajasthan Royals',
          "ligaOf" => 'Indian Premier League',
          "matchDate" => 11,
        ],
        [
          "matchTime" => '21:10',
          "team_1" => 'Gerwyn Price',
          "team_2" => 'Nathan  Aspinall',
          "ligaOf" => 'Premier League Darts',
          "matchDate" => 11,
        ],
        [
          "matchTime" => '21:30',
          "team_1" => 'Celtic (W)',
          "team_2" => 'Glasgow City (W)',
          "ligaOf" => "Scottish Women's Premier League",
          "matchDate" => 11,
        ],
        [
          "matchTime" => '21:40',
          "team_1" => 'Chris Dobey',
          "team_2" => 'Peter Wright',
          "ligaOf" => 'Premier League Darts',
          "matchDate" => 11,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Fiorentina',
          "team_2" => 'FC Basel',
          "ligaOf" => 'Europa Conference League',
          "matchDate" => 11,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'West Ham',
          "team_2" => 'AZ Alkmaar',
          "ligaOf" => 'Europa Conference League',
          "matchDate" => 11,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Roma',
          "team_2" => 'Leverkusen',
          "ligaOf" => 'UEFA Europa League',
          "matchDate" => 11,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Juventus',
          "team_2" => 'Sevilla FC',
          "ligaOf" => 'UEFA Europa League',
          "matchDate" => 11,
        ],
        [
          "matchTime" => '22:10',
          "team_1" => 'Michael van Gerwen',
          "team_2" => 'Michael Smith',
          "ligaOf" => 'Premier League Darts',
          "matchDate" => 11,
        ],
        [
          "matchTime" => '22:40',
          "team_1" => 'Jonny Clayton',
          "team_2" => 'Dimitri van den Bergh',
          "ligaOf" => 'Premier League Darts',
          "matchDate" => 11,
        ],

        [
          "matchTime" => '00:00',
          "team_1" => 'TBC',
          "team_2" => 'TBC',
          "ligaOf" => 'Premier League Darts',
          "matchDate" => 12,
        ],
        [
          "matchTime" => '02:05',
          "team_1" => 'New York Yankees',
          "team_2" => 'Tampa Bay Rays',
          "ligaOf" => 'Major League Baseball',
          "matchDate" => 12,
        ],
        [
          "matchTime" => '02:05',
          "team_1" => 'Carolina Hurricanes',
          "team_2" => 'New Jersey Devils',
          "ligaOf" => 'NHL',
          "matchDate" => 12,
        ],
        [
          "matchTime" => '12:20',
          "team_1" => 'Richmond Tigers',
          "team_2" => 'Geelong Cats',
          "ligaOf" => 'AFL',
          "matchDate" => 12,
        ],
        [
          "matchTime" => '12:35',
          "team_1" => 'Western Force',
          "team_2" => 'Fijian Drua',
          "ligaOf" => 'Super Rugby Pacific',
          "matchDate" => 12,
        ],
        [
          "matchTime" => '12:45',
          "team_1" => 'Sydney FC',
          "team_2" => 'Melbourne City',
          "ligaOf" => 'Australian A-League Finals',
          "matchDate" => 12,
        ],
        [
          "matchTime" => '13:00',
          "team_1" => 'Penrith Panthers',
          "team_2" => 'Sydney Roosters',
          "ligaOf" => 'Australian NRL',
          "matchDate" => 12,
        ],
        [
          "matchTime" => '13:00',
          "team_1" => 'Surrey',
          "team_2" => 'Middlesex',
          "ligaOf" => 'LV County Championship',
          "matchDate" => 12,
        ],
        [
          "matchTime" => '16:20',
          "team_1" => 'Finland',
          "team_2" => 'USA',
          "ligaOf" => 'IIHF World Championship',
          "matchDate" => 12,
        ],
        [
          "matchTime" => '17:00',
          "team_1" => 'Mumbai Indians',
          "team_2" => 'Gujarat Titans',
          "ligaOf" => 'Indian Premier League',
          "matchDate" => 12,
        ],
        [
          "matchTime" => '18:05',
          "team_1" => 'The Pumas',
          "team_2" => 'Natal Sharks',
          "ligaOf" => 'Currie Cup',
          "matchDate" => 12,
        ],
        [
          "matchTime" => '20:20',
          "team_1" => 'Latvia',
          "team_2" => 'Canada',
          "ligaOf" => 'IIHF World Championship',
          "matchDate" => 12,
        ],
        [
          "matchTime" => '21:00',
          "team_1" => 'Team Bath',
          "team_2" => 'Manchester Thunder',
          "ligaOf" => 'Superleague',
          "matchDate" => 12,
        ],
        [
          "matchTime" => '21:35',
          "team_1" => 'Boroughmuir Bears',
          "team_2" => 'Watsonians',
          "ligaOf" => 'Super6',
          "matchDate" => 12,
        ],
        [
          "matchTime" => '21:45',
          "team_1" => 'Lazio',
          "team_2" => 'Lecce',
          "ligaOf" => 'Italian Serie A',
          "matchDate" => 12,
        ],
        [
          "matchTime" => '21:45',
          "team_1" => 'Queens Park',
          "team_2" => 'Partick',
          "ligaOf" => 'Scottish Premiership Play-off',
          "matchDate" => 12,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Burgos',
          "team_2" => 'Leganes',
          "ligaOf" => 'Spanish Segunda División',
          "matchDate" => 12,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Mallorca',
          "team_2" => 'Cadiz',
          "ligaOf" => 'Spanish La Liga',
          "matchDate" => 12,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Wigan Warriors',
          "team_2" => 'Leeds Rhinos',
          "ligaOf" => 'English Super League',
          "matchDate" => 12,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Lens',
          "team_2" => 'Reims',
          "ligaOf" => 'French Ligue 1',
          "matchDate" => 12,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Peterborough',
          "team_2" => 'Sheffield Wednesday',
          "ligaOf" => 'League One Playoff',
          "matchDate" => 12,
        ],
        [
          "matchTime" => '23:00',
          "team_1" => 'Mousasi',
          "team_2" => 'Edwards',
          "ligaOf" => 'MMA',
          "matchDate" => 12,
        ],

        [
          "matchTime" => '00:00',
          "team_1" => 'Ellis Zorro',
          "team_2" => 'Hosea Burton',
          "ligaOf" => 'Boxing',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '02:05',
          "team_1" => 'Toronto Blue Jays',
          "team_2" => 'Atlanta Braves',
          "ligaOf" => 'Major League Baseball',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '03:05',
          "team_1" => 'Los Angeles Lakers',
          "team_2" => 'Golden State Warriors',
          "ligaOf" => 'NBA',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '12:25',
          "team_1" => 'Brisbane Lions',
          "team_2" => 'Essendon Bombers',
          "ligaOf" => 'AFL',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '12:35',
          "team_1" => 'Canberra Raiders',
          "team_2" => 'Parramatta Eels',
          "ligaOf" => 'Australian NRL',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '12:45',
          "team_1" => 'Adelaide United',
          "team_2" => 'Central Coast',
          "ligaOf" => 'Australian A-League Finals',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '13:00',
          "team_1" => 'Sunrisers Hyderabad',
          "team_2" => 'Lucknow Super Giants',
          "ligaOf" => 'Indian Premier League',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '14:30',
          "team_1" => 'Leeds',
          "team_2" => 'Newcastle',
          "ligaOf" => 'Premier League',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '14:30',
          "team_1" => 'Rangers',
          "team_2" => 'Celtic',
          "ligaOf" => 'Scottish Premiership',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '15:00',
          "team_1" => 'St. Helens',
          "team_2" => 'Salford Red Devils',
          "ligaOf" => 'English Super League',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '15:00',
          "team_1" => 'Sociedad',
          "team_2" => 'Girona',
          "ligaOf" => 'Spanish La Liga',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '16:00',
          "team_1" => 'Salernitana',
          "team_2" => 'Atalanta',
          "ligaOf" => 'Italian Serie A',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '16:00',
          "team_1" => 'Perpignan',
          "team_2" => 'Toulouse',
          "ligaOf" => 'French Top 14',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '16:45',
          "team_1" => 'Sligo U20',
          "team_2" => 'Kildare U20',
          "ligaOf" => 'All-Ireland U20 Championship',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '17:00',
          "team_1" => 'Delhi Capitals',
          "team_2" => 'Punjab Kings',
          "ligaOf" => 'Indian Premier League',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '17:00',
          "team_1" => 'Bolton',
          "team_2" => 'Barnsley',
          "ligaOf" => 'League One Playoff',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '17:00',
          "team_1" => 'Stormers',
          "team_2" => 'Connacht',
          "ligaOf" => 'United Rugby Championship',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '17:15',
          "team_1" => 'Gijon',
          "team_2" => 'Real Oviedo',
          "ligaOf" => 'Spanish Segunda División',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '17:15',
          "team_1" => 'Osasuna',
          "team_2" => 'Almeria',
          "ligaOf" => 'Spanish La Liga',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '17:30',
          "team_1" => 'Saracens',
          "team_2" => 'Northampton Saints',
          "ligaOf" => 'Premiership Rugby',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '17:30',
          "team_1" => 'Chesterfield',
          "team_2" => 'Notts County',
          "ligaOf" => 'English BlueSq Play-off',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '18:00',
          "team_1" => 'Strasbourg',
          "team_2" => 'Nice',
          "ligaOf" => 'French Ligue 1',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '18:00',
          "team_1" => 'Bordeaux Begles',
          "team_2" => 'Pau',
          "ligaOf" => 'French Top 14',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '18:45',
          "team_1" => 'Cavan',
          "team_2" => 'Laois',
          "ligaOf" => 'Tailteann Cup',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '19:00',
          "team_1" => 'Spezia',
          "team_2" => 'AC Milan',
          "ligaOf" => 'Italian Serie A',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '19:15',
          "team_1" => 'Newtown AFC',
          "team_2" => 'Haverfordwest County',
          "ligaOf" => 'Welsh Premier League Play-off',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '19:30',
          "team_1" => 'Borussia Dortmund',
          "team_2" => 'Mgladbach',
          "ligaOf" => 'German Bundesliga',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '19:30',
          "team_1" => 'Granada',
          "team_2" => 'Lugo',
          "ligaOf" => 'Spanish Segunda División',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '19:30',
          "team_1" => 'Zaragoza',
          "team_2" => 'Cartagena',
          "ligaOf" => 'Spanish Segunda División',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '19:30',
          "team_1" => 'Villarreal',
          "team_2" => 'Ath Bilbao',
          "ligaOf" => 'Spanish La Liga',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '19:30',
          "team_1" => 'Ayrshire Bulls',
          "team_2" => 'Heriots Rugby',
          "ligaOf" => 'Super6',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '19:30',
          "team_1" => 'Sunderland',
          "team_2" => 'Luton',
          "ligaOf" => 'English Championship Play-off',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '19:30',
          "team_1" => 'Leinster',
          "team_2" => 'Munster',
          "ligaOf" => 'United Rugby Championship',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '19:30',
          "team_1" => 'Michigan Panthers',
          "team_2" => 'Pittsburgh Maulers',
          "ligaOf" => 'US USFL',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '20:00',
          "team_1" => 'KSI',
          "team_2" => 'Joe Fournier',
          "ligaOf" => 'Boxing',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '20:00',
          "team_1" => 'Portimonense',
          "team_2" => 'Benfica',
          "ligaOf" => 'Liga NOS',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '20:00',
          "team_1" => 'Waterford (H)',
          "team_2" => 'Clare (H)',
          "ligaOf" => 'All Ireland Senior Hurling Championship',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '20:20',
          "team_1" => 'Germany',
          "team_2" => 'Finland',
          "ligaOf" => 'IIHF World Championship',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '21:45',
          "team_1" => 'Inter',
          "team_2" => 'Sassuolo',
          "ligaOf" => 'Italian Serie A',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '21:45',
          "team_1" => 'Salford City',
          "team_2" => 'Stockport County',
          "ligaOf" => 'English Division Two Play-off',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Malaga',
          "team_2" => 'Mirandes',
          "ligaOf" => 'Spanish Segunda División',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Real Madrid',
          "team_2" => 'Getafe',
          "ligaOf" => 'Spanish La Liga',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Rosenstruik',
          "team_2" => 'Almeida',
          "ligaOf" => 'UFC',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Paris',
          "team_2" => 'Ajaccio',
          "ligaOf" => 'French Ligue 1',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '23:00',
          "team_1" => 'Birmingham Stallions',
          "team_2" => 'Houston Gamblers',
          "ligaOf" => 'US USFL',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '23:05',
          "team_1" => 'Oakland Athletics',
          "team_2" => 'Texas Rangers',
          "ligaOf" => 'Major League Baseball',
          "matchDate" => 13,
        ],
        [
          "matchTime" => '02:05',
          "team_1" => 'Seattle Kraken',
          "team_2" => 'Dallas Stars',
          "ligaOf" => 'NHL',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '02:15',
          "team_1" => 'Los Angeles Dodgers',
          "team_2" => 'San Diego Padres',
          "ligaOf" => 'Major League Baseball',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '13:00',
          "team_1" => 'Rajasthan Royals',
          "team_2" => 'Royal Challengers Bangalore',
          "ligaOf" => 'Indian Premier League',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '13:00',
          "team_1" => 'Surrey',
          "team_2" => 'Middlesex',
          "ligaOf" => 'LV County Championship',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '13:30',
          "team_1" => 'Verona',
          "team_2" => 'Torino',
          "ligaOf" => 'Italian Serie A',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '14:00',
          "team_1" => 'Clermont',
          "team_2" => 'Lyon',
          "ligaOf" => 'French Ligue 1',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '14:00',
          "team_1" => 'Coventry',
          "team_2" => 'Middlesbrough',
          "ligaOf" => 'English Championship Play-off',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '14:30',
          "team_1" => 'Oxford City',
          "team_2" => 'St Albans',
          "ligaOf" => 'National League South Play-off',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '15:00',
          "team_1" => 'Santander',
          "team_2" => 'Eibar',
          "ligaOf" => 'Spanish Segunda División',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '15:00',
          "team_1" => 'Celta Vigo',
          "team_2" => 'Valencia',
          "ligaOf" => 'Spanish La Liga',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '15:10',
          "team_1" => 'Hibernian (W)',
          "team_2" => 'Celtic (W)',
          "ligaOf" => "Scottish Women's Premier League",
          "matchDate" => 14,
        ],
        [
          "matchTime" => '15:15',
          "team_1" => 'London Lions (W)',
          "team_2" => 'Leicester Riders (W)',
          "ligaOf" => 'WNBL',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '15:30',
          "team_1" => 'Groningen',
          "team_2" => 'Ajax',
          "ligaOf" => 'Dutch Division 1',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '15:45',
          "team_1" => 'Dublin',
          "team_2" => 'Louth',
          "ligaOf" => 'All Ireland Senior Football Championship',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '16:00',
          "team_1" => 'Everton',
          "team_2" => 'Man City',
          "ligaOf" => 'Premier League',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '16:00',
          "team_1" => 'Fiorentina',
          "team_2" => 'Udinese',
          "ligaOf" => 'Italian Serie A',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '16:00',
          "team_1" => 'Monza',
          "team_2" => 'Napoli',
          "ligaOf" => 'Italian Serie A',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '16:00',
          "team_1" => 'Toulouse',
          "team_2" => 'Nantes',
          "ligaOf" => 'French Ligue 1',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '16:30',
          "team_1" => 'Stuttgart',
          "team_2" => 'Leverkusen',
          "ligaOf" => 'German Bundesliga',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '16:30',
          "team_1" => 'Chelsea (W)',
          "team_2" => 'Man Utd (W)',
          "ligaOf" => 'English FA Cup (W)',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '17:00',
          "team_1" => 'Sale Sharks',
          "team_2" => 'Leicester Tigers',
          "ligaOf" => 'Premiership Rugby',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '17:00',
          "team_1" => 'Chennai Super Kings',
          "team_2" => 'Kolkata Knight Riders',
          "ligaOf" => 'Indian Premier League',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '17:15',
          "team_1" => 'FC Andorra',
          "team_2" => 'Tenerife',
          "ligaOf" => 'Spanish Segunda División',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '17:15',
          "team_1" => 'Elche',
          "team_2" => 'Atl Madrid',
          "ligaOf" => 'Spanish La Liga',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '17:30',
          "team_1" => 'Brackley Town',
          "team_2" => 'Kidderminster',
          "ligaOf" => 'National League North Play-off',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '17:45',
          "team_1" => 'Feyenoord',
          "team_2" => 'Go Ahead Eagles',
          "ligaOf" => 'Dutch Division 1',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '18:00',
          "team_1" => 'Armagh',
          "team_2" => 'Derry',
          "ligaOf" => 'All Ireland Senior Football Championship',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '18:05',
          "team_1" => 'Monaco',
          "team_2" => 'Lille',
          "ligaOf" => 'French Ligue 1',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '18:10',
          "team_1" => 'Glasgow City (W)',
          "team_2" => 'Partick (W)',
          "ligaOf" => "Scottish Women's Premier League",
          "matchDate" => 14,
        ],
        [
          "matchTime" => '18:30',
          "team_1" => 'Arsenal',
          "team_2" => 'Brighton',
          "ligaOf" => 'Premier League',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '18:30',
          "team_1" => 'RB Leipzig',
          "team_2" => 'W Bremen',
          "ligaOf" => 'German Bundesliga',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '19:00',
          "team_1" => 'Bologna',
          "team_2" => 'Roma',
          "ligaOf" => 'Italian Serie A',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '19:00',
          "team_1" => 'Philadelphia Stars',
          "team_2" => 'New Jersey Generals',
          "ligaOf" => 'US USFL',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '19:30',
          "team_1" => 'Huesca',
          "team_2" => 'Ponferradina',
          "ligaOf" => 'Spanish Segunda División',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '19:30',
          "team_1" => 'Albacete',
          "team_2" => 'Alaves',
          "ligaOf" => 'Spanish Segunda División',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '19:30',
          "team_1" => 'Valladolid',
          "team_2" => 'Sevilla FC',
          "ligaOf" => 'Spanish La Liga',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '20:37',
          "team_1" => 'Toronto Blue Jays',
          "team_2" => 'Atlanta Braves',
          "ligaOf" => 'Major League Baseball',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '21:00',
          "team_1" => 'Bradford',
          "team_2" => 'Carlisle',
          "ligaOf" => 'English Division Two Play-off',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '21:45',
          "team_1" => 'Juventus',
          "team_2" => 'Cremonese',
          "ligaOf" => 'Italian Serie A',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '21:45',
          "team_1" => 'Marseille',
          "team_2" => 'Angers',
          "ligaOf" => 'French Ligue 1',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Las Palmas',
          "team_2" => 'Villarreal B',
          "ligaOf" => 'Spanish Segunda División',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Espanyol',
          "team_2" => 'Barcelona',
          "ligaOf" => 'Spanish La Liga',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'New Orleans Breakers',
          "team_2" => 'Memphis Showboats',
          "ligaOf" => 'US USFL',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '22:35',
          "team_1" => 'Boston Celtics',
          "team_2" => 'Philadelphia 76ers',
          "ligaOf" => 'NBA',
          "matchDate" => 14,
        ],
        [
          "matchTime" => '23:10',
          "team_1" => 'Los Angeles Dodgers',
          "team_2" => 'San Diego Padres',
          "ligaOf" => 'Major League Baseball',
          "matchDate" => 14,
        ],

        [
          "matchTime" => '00:30',
          "team_1" => 'Sky Blue (W)',
          "team_2" => 'Orlando Pride (W)',
          "ligaOf" => 'US Womens Division 1',
          "matchDate" => 15,
        ],
        [
          "matchTime" => '01:00',
          "team_1" => 'Kansas City (W)',
          "team_2" => 'San Diego Wave (W)',
          "ligaOf" => 'US Womens Division 1',
          "matchDate" => 15,
        ],
        [
          "matchTime" => '02:05',
          "team_1" => 'Boston Red Sox',
          "team_2" => 'St Louis Cardinals',
          "ligaOf" => 'Major League Baseball',
          "matchDate" => 15,
        ],
        [
          "matchTime" => '16:20',
          "team_1" => 'Slovakia',
          "team_2" => 'Canada',
          "ligaOf" => 'IIHF World Championship',
          "matchDate" => 15,
        ],
        [
          "matchTime" => '17:00',
          "team_1" => 'Gujarat Titans',
          "team_2" => 'Sunrisers Hyderabad',
          "ligaOf" => 'Indian Premier League',
          "matchDate" => 15,
        ],
        [
          "matchTime" => '20:20',
          "team_1" => 'Finland',
          "team_2" => 'Sweden',
          "ligaOf" => 'IIHF World Championship',
          "matchDate" => 15,
        ],
        [
          "matchTime" => '21:45',
          "team_1" => 'Sampdoria',
          "team_2" => 'Empoli',
          "ligaOf" => 'Italian Serie A',
          "matchDate" => 15,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Leicester',
          "team_2" => 'Liverpool',
          "ligaOf" => 'Premier League',
          "matchDate" => 15,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Levante',
          "team_2" => 'Ibiza Eivissa',
          "ligaOf" => 'Spanish Segunda División',
          "matchDate" => 15,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Betis',
          "team_2" => 'Rayo Vallecano',
          "ligaOf" => 'Spanish La Liga',
          "matchDate" => 15,
        ],
        [
          "matchTime" => '23:05',
          "team_1" => 'Washington Nationals',
          "team_2" => 'New York Mets',
          "ligaOf" => 'Major League Baseball',
          "matchDate" => 15,
        ],
        [
          "matchTime" => '17:00',
          "team_1" => 'Lucknow Super Giants',
          "team_2" => 'Mumbai Indians',
          "ligaOf" => 'Indian Premier League',
          "matchDate" => 16,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Inter',
          "team_2" => 'AC Milan',
          "ligaOf" => 'UEFA Champions League',
          "matchDate" => 16,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Luton',
          "team_2" => 'Sunderland',
          "ligaOf" => 'English Championship Play-off',
          "matchDate" => 16,
        ],

        [
          "matchTime" => '17:00',
          "team_1" => 'Punjab Kings',
          "team_2" => 'Delhi Capitals',
          "ligaOf" => 'Indian Premier League',
          "matchDate" => 17,
        ],
        [
          "matchTime" => '19:00',
          "team_1" => 'Sweden U17 (W)',
          "team_2" => 'England U17 (W)',
          "ligaOf" => "UEFA Women's U17 Championship",
          "matchDate" => 17,
        ],
        [
          "matchTime" => '20:15',
          "team_1" => 'Everton (W)',
          "team_2" => 'Arsenal (W)',
          "ligaOf" => "English Women's Super League",
          "matchDate" => 17,
        ],
        [
          "matchTime" => '21:35',
          "team_1" => 'TBC',
          "team_2" => 'TBC',
          "ligaOf" => 'Scottish Div 1 Play-off',
          "matchDate" => 17,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Man City',
          "team_2" => 'Real Madrid',
          "ligaOf" => 'UEFA Champions League',
          "matchDate" => 17,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Middlesbrough',
          "team_2" => 'Coventry',
          "ligaOf" => 'English Championship Play-off',
          "matchDate" => 17,
        ],
        [
          "matchTime" => '22:10',
          "team_1" => 'Los Angeles Dodgers',
          "team_2" => 'Minnesota Twins',
          "ligaOf" => 'Major League Baseball',
          "matchDate" => 17,
        ],
        [
          "matchTime" => '22:15',
          "team_1" => 'West Ham (W)',
          "team_2" => 'Chelsea (W)',
          "ligaOf" => "English Women's Super League",
          "matchDate" => 17,
        ],
        [
          "matchTime" => '12:50',
          "team_1" => 'Brisbane Broncos',
          "team_2" => 'Penrith Panthers',
          "ligaOf" => 'Australian NRL',
          "matchDate" => 18,
        ],
        [
          "matchTime" => '17:00',
          "team_1" => 'Sunrisers Hyderabad',
          "team_2" => 'Royal Challengers Bangalore',
          "ligaOf" => 'Indian Premier League',
          "matchDate" => 18,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'FC Basel',
          "team_2" => 'Fiorentina',
          "ligaOf" => 'Europa Conference League',
          "matchDate" => 18,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'AZ Alkmaar',
          "team_2" => 'West Ham',
          "ligaOf" => 'Europa Conference League',
          "matchDate" => 18,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Leverkusen',
          "team_2" => 'Roma',
          "ligaOf" => 'UEFA Europa League',
          "matchDate" => 18,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Sevilla FC',
          "team_2" => 'Juventus',
          "ligaOf" => 'UEFA Europa League',
          "matchDate" => 18,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Sheffield Wednesday',
          "team_2" => 'Peterborough',
          "ligaOf" => 'League One Playoff',
          "matchDate" => 18,
        ],
        [
          "matchTime" => '22:30',
          "team_1" => 'Newcastle',
          "team_2" => 'Brighton',
          "ligaOf" => 'Premier League',
          "matchDate" => 18,
        ],

        [
          "matchTime" => '12:45',
          "team_1" => 'Melbourne City',
          "team_2" => 'Sydney FC',
          "ligaOf" => 'Australian A-League Finals',
          "matchDate" => 19,
        ],
        [
          "matchTime" => '13:00',
          "team_1" => 'South Sydney Rabbitohs',
          "team_2" => 'Parramatta Eels',
          "ligaOf" => 'Australian NRL',
          "matchDate" => 19,
        ],
        [
          "matchTime" => '21:30',
          "team_1" => 'Freiburg',
          "team_2" => 'Wolfsburg',
          "ligaOf" => 'German Bundesliga',
          "matchDate" => 19,
        ],
        [
          "matchTime" => '21:35',
          "team_1" => 'Ayrshire Bulls',
          "team_2" => 'Watsonians',
          "ligaOf" => 'Super6',
          "matchDate" => 19,
        ],
        [
          "matchTime" => '21:45',
          "team_1" => 'Sassuolo',
          "team_2" => 'Monza',
          "ligaOf" => 'Italian Serie A',
          "matchDate" => 19,
        ],
        [
          "matchTime" => '21:45',
          "team_1" => 'Halifax RLFC',
          "team_2" => 'St. Helens',
          "ligaOf" => 'English Challenge Cup',
          "matchDate" => 19,
        ],
        [
          "matchTime" => '21:45',
          "team_1" => 'TBC',
          "team_2" => 'Ayr Utd',
          "ligaOf" => 'Scottish Premiership Play-off',
          "matchDate" => 19,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Lyon',
          "team_2" => 'Monaco',
          "ligaOf" => 'French Ligue 1',
          "matchDate" => 19,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Glasgow Warriors',
          "team_2" => 'Toulon',
          "ligaOf" => 'European Challenge Cup',
          "matchDate" => 19,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Barnsley',
          "team_2" => 'Bolton',
          "ligaOf" => 'League One Playoff',
          "matchDate" => 19,
        ],

        [
          "matchTime" => '12:35',
          "team_1" => 'Dolphins',
          "team_2" => 'Melbourne Storm',
          "ligaOf" => 'Australian NRL',
          "matchDate" => 20,
        ],
        [
          "matchTime" => '14:30',
          "team_1" => 'Tottenham',
          "team_2" => 'Brentford',
          "ligaOf" => 'Premier League',
          "matchDate" => 20,
        ],
        [
          "matchTime" => '14:30',
          "team_1" => 'Stockport County',
          "team_2" => 'Salford City',
          "ligaOf" => 'English Division Two Play-off',
          "matchDate" => 20,
        ],
        [
          "matchTime" => '15:00',
          "team_1" => 'Western Force',
          "team_2" => 'ACT Brumbies',
          "ligaOf" => 'Super Rugby Pacific',
          "matchDate" => 20,
        ],
        [
          "matchTime" => '15:00',
          "team_1" => 'Girona',
          "team_2" => 'Villarreal',
          "ligaOf" => 'Spanish La Liga',
          "matchDate" => 20,
        ],
        [
          "matchTime" => '16:00',
          "team_1" => 'Derbyshire',
          "team_2" => 'Lancashire',
          "ligaOf" => 'T20 Blast',
          "matchDate" => 20,
        ],
        [
          "matchTime" => '16:30',
          "team_1" => 'Leeds Rhinos',
          "team_2" => 'Wigan Warriors',
          "ligaOf" => 'English Challenge Cup',
          "matchDate" => 20,
        ],
        [
          "matchTime" => '17:00',
          "team_1" => 'Carlisle',
          "team_2" => 'Bradford',
          "ligaOf" => 'English Division Two Play-off',
          "matchDate" => 20,
        ],
        [
          "matchTime" => '17:00',
          "team_1" => 'Kerry',
          "team_2" => 'Mayo',
          "ligaOf" => 'All Ireland Senior Football Championship',
          "matchDate" => 20,
        ],
        [
          "matchTime" => '18:45',
          "team_1" => 'Leinster',
          "team_2" => 'La Rochelle',
          "ligaOf" => 'European Rugby Champions Cup',
          "matchDate" => 20,
        ],
        [
          "matchTime" => '19:00',
          "team_1" => 'Atalanta',
          "team_2" => 'Verona',
          "ligaOf" => 'Italian Serie A',
          "matchDate" => 20,
        ],
        [
          "matchTime" => '19:15',
          "team_1" => 'TBC',
          "team_2" => 'TBC',
          "ligaOf" => 'Scottish Div 1 Play-off',
          "matchDate" => 20,
        ],
        [
          "matchTime" => '19:15',
          "team_1" => 'Galway',
          "team_2" => 'Tyrone',
          "ligaOf" => 'All Ireland Senior Football Championship',
          "matchDate" => 20,
        ],
        [
          "matchTime" => '19:30',
          "team_1" => 'B Munich',
          "team_2" => 'RB Leipzig',
          "ligaOf" => 'German Bundesliga',
          "matchDate" => 20,
        ],
        [
          "matchTime" => '19:30',
          "team_1" => 'Nottingham Forest',
          "team_2" => 'Arsenal',
          "ligaOf" => 'Premier League',
          "matchDate" => 20,
        ],
        [
          "matchTime" => '20:00',
          "team_1" => 'Kilkenny (H)',
          "team_2" => 'Dublin (H)',
          "ligaOf" => 'All Ireland Senior Hurling Championship',
          "matchDate" => 20,
        ],
        [
          "matchTime" => '20:00',
          "team_1" => 'Leitrim',
          "team_2" => 'Fermangh',
          "ligaOf" => 'Tailteann Cup',
          "matchDate" => 20,
        ],
        [
          "matchTime" => '20:15',
          "team_1" => 'Birmingham Bears',
          "team_2" => 'Yorkshire',
          "ligaOf" => 'T20 Blast',
          "matchDate" => 20,
        ],
        [
          "matchTime" => '21:30',
          "team_1" => 'Salford Red Devils',
          "team_2" => 'Huddersfield Giants',
          "ligaOf" => 'English Challenge Cup',
          "matchDate" => 20,
        ],
        [
          "matchTime" => '21:45',
          "team_1" => 'AC Milan',
          "team_2" => 'Sampdoria',
          "ligaOf" => 'Italian Serie A',
          "matchDate" => 20,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Lille',
          "team_2" => 'Marseille',
          "ligaOf" => 'French Ligue 1',
          "matchDate" => 20,
        ],
        [
          "matchTime" => '22:00',
          "team_1" => 'Barcelona',
          "team_2" => 'Sociedad',
          "ligaOf" => 'Spanish La Liga',
          "matchDate" => 20,
        ],
        ["matchTime" => "00:00","team_1" => "Katie Taylor","team_2" => "Chantelle Cameron","ligaOf" => "Boxing","matchDate" => 21],
["matchTime" => "02:00","team_1" => "UFC Fight Night - Dern","team_2" => "Hill","ligaOf" => "UFC","matchDate" => 21],
["matchTime" => "02:15","team_1" => "Atlanta Braves","team_2" => "Seattle Mariners","ligaOf" => "Major League Baseball","matchDate" => 21],
["matchTime" => "05:00","team_1" => "Devin Haney","team_2" => "Vasiliy Lomachenko","ligaOf" => "Boxing","matchDate" => 21],
["matchTime" => "13:00","team_1" => "Mumbai Indians","team_2" => "Sunrisers Hyderabad","ligaOf" => "Indian Premier League","matchDate" => 21],
["matchTime" => "13:30","team_1" => "Lecce","team_2" => "Spezia","ligaOf" => "Italian Serie A","matchDate" => 21],
["matchTime" => "14:00","team_1" => "Hibernian","team_2" => "Rangers","ligaOf" => "Scottish Premiership","matchDate" => 21],
["matchTime" => "14:00","team_1" => "Ajaccio","team_2" => "Rennes","ligaOf" => "French Ligue 1","matchDate" => 21],
["matchTime" => "14:15","team_1" => "Ascot Utd","team_2" => "Newport Pagnell Town","ligaOf" => "FA Vase","matchDate" => 21],
["matchTime" => "14:30","team_1" => "Chelsea (W)","team_2" => "Arsenal (W)","ligaOf" => "English Women's Super League","matchDate" => 21],
["matchTime" => "15:00","team_1" => "Rayo Vallecano","team_2" => "Espanyol","ligaOf" => "Spanish La Liga","matchDate" => 21],
["matchTime" => "15:30","team_1" => "West Ham","team_2" => "Leeds","ligaOf" => "Premier League","matchDate" => 21],
["matchTime" => "16:00","team_1" => "Torino","team_2" => "Fiorentina","ligaOf" => "Italian Serie A","matchDate" => 21],
["matchTime" => "16:00","team_1" => "Nice","team_2" => "Toulouse","ligaOf" => "French Ligue 1","matchDate" => 21],
["matchTime" => "16:00","team_1" => "Clare (H)","team_2" => "Cork (H)","ligaOf" => "All Ireland Senior Hurling Championship","matchDate" => 21],
["matchTime" => "16:30","team_1" => "Mainz","team_2" => "Stuttgart","ligaOf" => "German Bundesliga","matchDate" => 21],
["matchTime" => "17:00","team_1" => "Castleford Tigers","team_2" => "Hull FC","ligaOf" => "English Challenge Cup","matchDate" => 21],
["matchTime" => "17:00","team_1" => "Royal Challengers Bangalore","team_2" => "Gujarat Titans","ligaOf" => "Indian Premier League","matchDate" => 21],
["matchTime" => "17:15","team_1" => "Atl Madrid","team_2" => "Osasuna","ligaOf" => "Spanish La Liga","matchDate" => 21],
["matchTime" => "17:15","team_1" => "Real Oviedo","team_2" => "Santander","ligaOf" => "Spanish Segunda División","matchDate" => 21],
["matchTime" => "18:00","team_1" => "Man City","team_2" => "Chelsea","ligaOf" => "Premier League","matchDate" => 21],
["matchTime" => "18:00","team_1" => "Tipperary (H)","team_2" => "Limerick (H)","ligaOf" => "All Ireland Senior Hurling Championship","matchDate" => 21],
["matchTime" => "18:05","team_1" => "Lorient","team_2" => "Lens","ligaOf" => "French Ligue 1","matchDate" => 21],
["matchTime" => "18:15","team_1" => "FC Halifax Town","team_2" => "Gateshead","ligaOf" => "English FA Trophy","matchDate" => 21],
["matchTime" => "18:30","team_1" => "Augsburg","team_2" => "Borussia Dortmund","ligaOf" => "German Bundesliga","matchDate" => 21],
["matchTime" => "19:00","team_1" => "Napoli","team_2" => "Inter","ligaOf" => "Italian Serie A","matchDate" => 21],
["matchTime" => "19:30","team_1" => "Valencia","team_2" => "Real Madrid","ligaOf" => "Spanish La Liga","matchDate" => 21],
["matchTime" => "19:30","team_1" => "Leganes","team_2" => "FC Andorra","ligaOf" => "Spanish Segunda División","matchDate" => 21],
["matchTime" => "20:30","team_1" => "Leverkusen","team_2" => "Mgladbach","ligaOf" => "German Bundesliga","matchDate" => 21],
["matchTime" => "20:45","team_1" => "Man Utd (W)","team_2" => "Man City (W)","ligaOf" => "English Women's Super League","matchDate" => 21],
["matchTime" => "21:45","team_1" => "Udinese","team_2" => "Lazio","ligaOf" => "Italian Serie A","matchDate" => 21],
["matchTime" => "21:45","team_1" => "Auxerre","team_2" => "Paris","ligaOf" => "French Ligue 1","matchDate" => 21],
["matchTime" => "22:00","team_1" => "Sevilla FC","team_2" => "Betis","ligaOf" => "Spanish La Liga","matchDate" => 21],
["matchTime" => "22:30","team_1" => "Sporting Lisbon","team_2" => "Benfica","ligaOf" => "Liga NOS","matchDate" => 21],

["matchTime" => "02:05","team_1" => "New York Mets","team_2" => "Cleveland Indians","ligaOf" => "Major League Baseball","matchDate" => 22],
["matchTime" => "19:30","team_1" => "Roma","team_2" => "Salernitana","ligaOf" => "Italian Serie A","matchDate" => 22],
["matchTime" => "21:45","team_1" => "Empoli","team_2" => "Juventus","ligaOf" => "Italian Serie A","matchDate" => 22],
["matchTime" => "22:00","team_1" => "Newcastle","team_2" => "Leicester","ligaOf" => "Premier League","matchDate" => 22],

["matchTime" => "01:35","team_1" => "Pittsburgh Pirates","team_2" => "Texas Rangers","ligaOf" => "Major League Baseball","matchDate" => 23],
["matchTime" => "20:30","team_1" => "Celta Vigo","team_2" => "Girona","ligaOf" => "Spanish La Liga","matchDate" => 23],
["matchTime" => "20:30","team_1" => "Sociedad","team_2" => "Almeria","ligaOf" => "Spanish La Liga","matchDate" => 23],
["matchTime" => "23:00","team_1" => "Valladolid","team_2" => "Barcelona","ligaOf" => "Spanish La Liga","matchDate" => 23]

      ];

      echo json_encode($translations);

